<a href="https://colab.research.google.com/github/Harshit-563/Agent_Coco/blob/main/Pytorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [ ]:
df.shape

(569, 33)

In [ ]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [ ]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,fractal_dimension_mean,radius_se,texture_se,perimeter_se,area_se,smoothness_se,compactness_se,concavity_se,concave points_se,symmetry_se,fractal_dimension_se,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,1.0950,0.9053,8.589,153.40,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.01860,0.01340,0.01389,0.003532,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,0.7456,0.7869,4.585,94.03,0.006150,0.04006,0.03832,0.02058,0.02250,0.004571,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,0.4956,1.1560,3.445,27.23,0.009110,0.07458,0.05661,0.01867,0.05963,0.009208,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,0.7572,0.7813,5.438,94.44,0.011490,0.02461,0.05688,0.01885,0.01756,0.005115,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [ ]:
X_train,X_test,y_train,y_test= train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [ ]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [ ]:
X_train

array([[-6.21345369e-01, -1.07203703e+00, -5.59274537e-01, ...,
        -8.11672995e-01, -2.82704499e-01,  1.05446046e+00],
       [-4.29896772e-01, -3.02985476e-03, -3.98358770e-01, ...,
        -3.21445325e-01, -1.23538363e+00, -6.43965062e-01],
       [-1.24732427e+00, -8.25343067e-01, -1.26079971e+00, ...,
        -9.45979862e-01, -1.03487634e-01, -1.15482721e-01],
       ...,
       [-7.60580712e-01,  3.13802589e-01, -5.81659146e-01, ...,
         2.18597110e+00,  5.86569166e+00,  4.77043558e+00],
       [ 7.12993336e-01, -1.91678180e-01,  6.44003737e-01, ...,
        -3.43043938e-01, -8.06206397e-01, -1.02894865e+00],
       [-4.11981060e-02, -5.95579081e-01, -1.00601246e-01, ...,
        -7.84294472e-01, -3.58164232e-01, -3.70889080e-01]])

In [ ]:
y_train

,diagnosis
145,B
355,B
273,B
298,B
454,B
...,...
425,B
69,B
3,M
363,B


In [ ]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.fit_transform(y_test)

In [ ]:
y_train

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,

In [ ]:
X_train_tensor =torch.from_numpy(X_train)
X_test_tensor =torch.from_numpy(X_test)
y_train_tensor =torch.from_numpy(y_train)
y_test_tensor =torch.from_numpy(y_test)


In [ ]:
X_train_tensor

tensor([[-6.2135e-01, -1.0720e+00, -5.5927e-01,  ..., -8.1167e-01,
         -2.8270e-01,  1.0545e+00],
        [-4.2990e-01, -3.0299e-03, -3.9836e-01,  ..., -3.2145e-01,
         -1.2354e+00, -6.4397e-01],
        [-1.2473e+00, -8.2534e-01, -1.2608e+00,  ..., -9.4598e-01,
         -1.0349e-01, -1.1548e-01],
        ...,
        [-7.6058e-01,  3.1380e-01, -5.8166e-01,  ...,  2.1860e+00,
          5.8657e+00,  4.7704e+00],
        [ 7.1299e-01, -1.9168e-01,  6.4400e-01,  ..., -3.4304e-01,
         -8.0621e-01, -1.0289e+00],
        [-4.1198e-02, -5.9558e-01, -1.0060e-01,  ..., -7.8429e-01,
         -3.5816e-01, -3.7089e-01]], dtype=torch.float64)

In [ ]:
y_train_tensor.shape

torch.Size([455])

In [ ]:
class MysimpleNN():
  def __init__(self,X):
    self.weights=torch.randn(X.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,X):
    z=torch.matmul(X,self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    epsilon=1e-7
    y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    loss=-(y_train_tensor*torch.log(y_pred)+(1 - y_train_tensor)*torch.log(1-y_pred)).mean()
    return loss

In [ ]:
learning_rate = 0.1
epochs = 10

In [ ]:
model=MysimpleNN(X_train_tensor)
model.weights

tensor([[-0.2770],
        [ 1.5334],
        [ 1.3168],
        [-1.1498],
        [ 1.0029],
        [ 0.0351],
        [ 0.9898],
        [-0.7458],
        [-0.9749],
        [-0.5554],
        [-0.0108],
        [ 1.0879],
        [-0.6828],
        [ 1.3023],
        [ 0.6573],
        [ 0.8650],
        [ 0.2753],
        [ 0.4916],
        [ 0.6257],
        [ 0.2903],
        [-0.6813],
        [-0.5224],
        [-0.4684],
        [-0.1241],
        [-0.0197],
        [-0.1179],
        [ 0.2215],
        [ 0.4121],
        [-0.6877],
        [ 0.2084]], dtype=torch.float64, requires_grad=True)

In [ ]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [ ]:
model=MysimpleNN(X_train_tensor)

for epoch in range(epochs):
  y_pred=model.forward(X_train_tensor)

  loss=model.loss_function(y_pred,y_train_tensor)
  print(f'Epoch:{epoch+1},Loss:{loss.item()}')

  loss.backward()
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad
    model.bias-=learning_rate*model.bias.grad

  model.weights.grad.zero_()
  model.bias.grad.zero_()




Epoch:1,Loss:1.4385280959161986
Epoch:2,Loss:1.3824931263872406
Epoch:3,Loss:1.3318269027256706
Epoch:4,Loss:1.286010312785433
Epoch:5,Loss:1.2445616673092634
Epoch:6,Loss:1.2070396201112408
Epoch:7,Loss:1.173044886697142
Epoch:8,Loss:1.1422221469644782
Epoch:9,Loss:1.1142601224403543
Epoch:10,Loss:1.0888876289612568


In [ ]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensor)
  y_pred=(y_pred>0.5).float()
  accuracy =(y_pred==y_test_tensor).float().mean()
print(f'Accuracy:{accuracy.item()}')




Accuracy:0.5053862929344177
